<Project Sdk="Microsoft.NET.Sdk">

  <ItemGroup>
    <Compile Remove="Common\NewFolder\**" />
    <EmbeddedResource Remove="Common\NewFolder\**" />
    <None Remove="Common\NewFolder\**" />
  </ItemGroup>

  <ItemGroup>
    <None Remove="FlashOffer.API.Application.csproj.Backup.tmp" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\FlashOffer.API.Domain\FlashOffer.API.Domain.csproj" />
    <ProjectReference Include="..\FlashOffer.API.Shared\FlashOffer.API.Shared.csproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="AutoMapper" />
    <PackageReference Include="AutoMapper.Extensions.Microsoft.DependencyInjection" />
    <PackageReference Include="FluentValidation.DependencyInjectionExtensions" />
    <PackageReference Include="MediatR" />
    <PackageReference Include="Microsoft.EntityFrameworkCore" />
    <PackageReference Include="Microsoft.Extensions.Localization.Abstractions" />
    <PackageReference Include="System.IdentityModel.Tokens.Jwt" />
  </ItemGroup>

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

</Project>
